### ISSUE TITLE
Running local_test_of_function using Python 3 mac gives TypeError: string indices must be integers

### ISSUE THREAD

**Issue by fe01134** [ibm-watson-iot/functions#65]
Steps to reproduce:
1.  Run  local_test_of_function.py on mac with virtual environment using Python 3.6.5
https://github.com/ibm-watson-iot/functions/blob/production/scripts/local_test_of_function.py
2.  Create credentials file. https://dashboard-us.connectedproducts.internetofthings.ibmcloud.com/dashboard
3.  python ./local_test_of_function.py
gives error:
```
2019-05-30T21:42:07.767 iotfunctions.enginelog.configure_console_logging DEBUG Console logging has been configured. Level = 10
Traceback (most recent call last):
  File "./local_test_of_function.py", line 27, in <module>
    db = Database(credentials=credentials)
  File "/Users/carlosferreira/jupyter/lib/python3.6/site-packages/iotfunctions/db.py", line 126, in __init__
    self.credentials['db2']['databaseName'] = self.credentials['db2']['database']
TypeError: string indices must be integers
```
4.

**Comment by herleraja** [comment]
If this issue still exists please create an issue in https://github.ibm.com/wiotp/monitoring-dashboard/issues.
